# .github/workflows/pre-commit.yml
name: Pre-commit Checks

on:
  pull_request:
    branches:
      - main # Or your default branch, e.g., 'master', 'develop'
  push:
    branches:
      - main # Optional: Also run on pushes to the main branch

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify your Python version, e.g., '3.9', '3.10', '3.11'

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv sync

      - name: Install pre-commit hooks
        run: |
          uv run pre-commit install-hooks

      - name: Run pre-commit checks
        run: |
          uv run pre-commit run --all-files
